# Basic Information 
title: Changhao Xu
position_1: Postdoc at Stanford
# position_2: 
affiliation: Ph.D. in MedE and CS, Caltech
affiliation_link: https://www.caltech.edu/
affiliation_logo: /assets/img/caltech_logo.png
email: changhaoxu14@gmail.com

# Search Engine Optimization (SEO)
keywords: changhao xu, xu changhao, changhaoxu, xuchanghao
canonical: https://chxu.me/
description: Changhao Xu is a newly minted Ph.D. from Caltech.
             His expertise lies in wearable devices, machine learning, and data science.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=X-1a2TgAAAAJ&hl=en
# cv_link: /assets/doc/CV_ChanghaoXu.pdf
github_link: https://github.com/Changhao-Xu
# github majority repositories are private consisting sensitive human studies data.
linkedin: https://www.linkedin.com/in/changhao-xu-023200143/
twitter: https://twitter.com/xu_changhao

# Images 
avatar: /assets/img/profile.jpg
favicon: /assets/img/favicon.png
favicon_dark: /assets/img/favicon-dark.png

# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
# enable_footnote: false

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: NHcwxXwwmQQod7FI724oAQ1rOf8OR_kZxp6X6te97VE

# Google Analytics ID
# Please remove this if you don't use Google Analytics
# google_analytics: ${{ secrets.GOOGLE_SCHOLAR_ID }}

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
